#!/bin/bash -e

# yet_another_backup_to_s3_solution cron skel file

PATH=$PATH:/root:/usr/bin
export PATH
export HOME=/root

@@YA_BACKUP_PATH@@ --bucket @@CONFIG_BUCKET@@ --backup-name @@CONFIG_PREFIX@@ @@ENCRYPTION@@ @@ENCRYPTION_FOR@@